variables:
  BINARY_NAME: $CI_PROJECT_NAME
  GO_PROJECT_NAMESPACE: rb3ckers  # $CI_PROJECT_NAMESPACE

.prep_go: &prep_go
  before_script:
    - export GL_URL=$(echo ${CI_PROJECT_URL:-https://github.com/rb3ckers/trafficmirror} | awk -F/ '{print $3}')
    - echo $GL_URL
    - echo export GO_PROJECT_PATH="$GOPATH/src/$GL_URL/$GO_PROJECT_NAMESPACE"
    - export GO_PROJECT_PATH="$GOPATH/src/$GL_URL/$GO_PROJECT_NAMESPACE"
    - rm -rf $GOPATH/src/$GL_URL
    - mkdir -p $GOPATH/src/$GL_URL
    - echo ln -s $(pwd) $GO_PROJECT_PATH
    - ln -s $(pwd) $GO_PROJECT_PATH
    - echo  export GO_PROJECT_PATH="$GO_PROJECT_PATH/$CI_PROJECT_NAME"
    - export GO_PROJECT_PATH="$GO_PROJECT_PATH/$CI_PROJECT_NAME"
    - cd $GO_PROJECT_PATH

stages:
  - build
#  - dockerbuild
#  - taglatest

go_build:
  <<: *prep_go
  stage: build
  image: golang:1.11
  script:
    - go get github.com/golang/dep/cmd/dep
    - dep ensure
    - mkdir -p build
    - ls -la $GO_PROJECT_PATH
    - env GOOS=linux GOARCH=amd64 go build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
